ALTER TABLE events ADD COLUMN IF NOT EXISTS rejection_reason TEXT DEFAULT '';
ALTER TABLE events ADD COLUMN IF NOT EXISTS approved_by VARCHAR(50) DEFAULT '';
ALTER TABLE events ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP;
